INSERT INTO PAIS(DESCRIPCION) VALUES ('Argentina');
INSERT INTO PAIS(DESCRIPCION) VALUES ('Paraguay');
INSERT INTO PAIS(DESCRIPCION) VALUES ('Peru');
INSERT INTO PAIS(DESCRIPCION) VALUES ('Bolivia');
INSERT INTO PAIS(DESCRIPCION) VALUES ('Venezuela');
INSERT INTO PAIS(DESCRIPCION) VALUES ('Brasil');

INSERT INTO TIPO_DOC(DESCRIPCION) VALUES ('DNI');
INSERT INTO TIPO_DOC(DESCRIPCION) VALUES ('CUIL');
INSERT INTO TIPO_DOC(DESCRIPCION) VALUES ('CUIT');

INSERT INTO TIPO_RELACION(DESCRIPCION) VALUES ('PADRE');

INSERT INTO PERSONA(NOMBRE, APELLIDO, ID_TIPO_DOC, NRO_DOCUMENTO, ID_PAIS, FECHA_NAC, NRO_CEL, NRO_ALT) VALUES ('Pedro', 'Garcia', 1, '20210548', 1, PARSEDATETIME('21-12-1990', 'dd-MM-yyyy'), '1110101155', '');
